// Our application state is generated by reducer functions
export default function() {
    return [
        {title: 'JavaScript: The Good Parts', pages: 234},
        {title: 'Harry Potter', pages: 123},
        {title: 'Dark Tower', pages: 23},
        {title: 'The Watering Hole', pages: 333},
        {title: 'Elequent Ruby', pages: 432}
    ];
}
